[[main]]
  name = "AI"
  pageRef = "/ai"
  weight = 10

[[main]]
  name = "投资"
  pageRef = "/investment"
  weight = 20

[[main]]
  name = "思考"
  pageRef = "/thoughts"
  weight = 30

[[main]]
  name = "关于"
  pageRef = "/about"
  weight = 40
