# -- zjdznl.github.io --
# 郭朕的个人网站 | Blowfish 主题
# https://blowfish.page/docs/

theme = "blowfish"
baseURL = "https://zjdznl.github.io/"
defaultContentLanguage = "zh-cn"

enableRobotsTXT = true
summaryLength = 70
hasCJKLanguage = true
enableEmoji = true

buildDrafts = false
buildFuture = true

[pagination]
  pagerSize = 100

[imaging]
  anchor = 'Center'

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[sitemap]
  changefreq = 'daily'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ["HTML", "RSS", "JSON"]

[related]
  threshold = 0
  toLower = false

  [[related.indices]]
    name = "tags"
    weight = 100
  [[related.indices]]
    name = "categories"
    weight = 100
  [[related.indices]]
    name = "series"
    weight = 50
  [[related.indices]]
    name = "authors"
    weight = 20
  [[related.indices]]
    name = "date"
    weight = 10
  [[related.indices]]
    applyFilter = false
    name = 'fragmentrefs'
    type = 'fragments'
    weight = 10
